# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: post-production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tarball
        run: tar -czvf "${{ github.repository }}.tar.gz" .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: post-production
    steps:
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Upload tarball to storage account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_KEY }} --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} --file "${{ github.repository }}.tar.gz" --name "${{ github.repository }}.tar.gz"
#Kick off workflow in post-production environment

##Signer01 env set

##Signer02 env set



#Set first environment approver

#Set second environment approver

#make TAR ball?

#Execute python tool for signing


##Copy to storage account

